# Generated by Django 5.1.7 on 2025-03-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectcomment_projectrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.project'),
        ),
    ]
